CREATE TABLE STATS (
	STAT_ID INT(11) AUTO_INCREMENT,
	STAT_DATE DATETIME NOT NULL,
	STAT VARCHAR(20) NOT NULL,
	VALUE INT(11) NOT NULL,
	PRIMARY KEY (STAT_ID)
);

CREATE VIEW BESTSELLERS_COUNT (TOTAL) AS
SELECT COUNT(*)
FROM BOOKS
WHERE BESTSELLER = TRUE;

DELIMITER |
CREATE EVENT UPDATE_BESTSELLERS
ON SCHEDULE EVERY 1 MINUTE
DO 
	BEGIN 
		CALL UpdateBestsellerValue();
		INSERT INTO STATS(STAT_DATE, STAT, VALUE)
		SELECT CURTIME(), "BESTSELLERS", BC.TOTAL
        	FROM BESTSELLERS_COUNT BC;
	END |
DELIMITER ;
