SELECT * FROM READERS
WHERE FIRSTNAME = "John";


CREATE INDEX READERSINDEX ON READERS (FIRSTNAME, LASTNAME);
CREATE INDEX BOOKSINDEX ON BOOKS (TITLE);

SELECT * FROM READERS
WHERE FIRSTNAME = "John";
